[book]
authors = ["Cosmo Chang"]
language = "zh-TW"
multilingual = false
src = "docs"
title = "非對稱防禦型美股策略指南：索提諾比率優化與雙向體制交易框架"

[output.html]
mathjax-support = true

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
